---
- hosts: localhost
  gather_facts: yes
  tasks:
    - name: create ~/.vim directories
      file:
        path: '~/.vim/{{ item }}'
        recurse: yes
        state: directory
      with_items:
        - autoload
        - bundle

    - name: install pathogen.vim
      get_url:
        url: https://tpo.pe/pathogen.vim
        dest: ~/.vim/autoload/pathogen.vim

    - name: clone vim plugins
      git:
        repo: '{{ item }}'
        dest: '~/.vim/bundle/{{ item | basename | replace(".git", "") }}'
      with_items:
        - git://github.com/bronson/vim-trailing-whitespace
        - git://github.com/dagwieers/asciidoc-vim
        - git://github.com/derekwyatt/vim-scala
        - git://github.com/fatih/vim-go
        - git://github.com/honza/dockerfile.vim
        - git://github.com/leshill/vim-json
        - git://github.com/rust-lang/rust.vim
        - git://github.com/tpope/vim-endwise
        - git://github.com/tpope/vim-fugitive
        - git://github.com/tpope/vim-haml
        - git://github.com/tpope/vim-markdown
        - git://github.com/tpope/vim-surround
        - git://github.com/vim-ruby/vim-ruby

    - name: copy .vimrc
      copy:
        src: files/vimrc
        dest: ~/.vimrc
        backup: yes

    - name: copy .tmux.conf
      template:
        src: files/tmux.conf
        dest: ~/.tmux.conf
        backup: yes

    - name: copy .gitconfig
      template:
        src: files/gitconfig.j2
        dest: ~/.gitconfig
        backup: yes

    - name: copy .gitignore_global
      template:
        src: files/gitignore_global
        dest: ~/.gitignore_global
        backup: yes
