---
- hosts: localhost
  gather_facts: yes
  tasks:
    - name: update homebrew
      homebrew:
        update_homebrew: yes
      when: ansible_distribution == 'MacOSX'

    - name: install homebrew packages
      homebrew:
        name: '{{ item }}'
      with_items:
        - asciidoc
        - autoconf
        - automake
        - cloc
        - cmake
        - csvkit
        - docker
        - docker-compose
        - docker-machine
        - dos2unix
        - fish
        - git
        - go
        - hub
        - jq
        - mercurial
        - protobuf
        - sqlite
        - the_silver_searcher
        - tmux
        - watchman
        - xmlto
      when: ansible_distribution == 'MacOSX'

    - name: install vim
      homebrew:
        name: vim
        install_options: with-python@2
      when: ansible_distribution == 'MacOSX'

    - name: create ~/.vim directories
      file:
        path: '~/.vim/{{ item }}'
        recurse: yes
        state: directory
      with_items:
        - autoload
        - bundle

    - name: install pathogen.vim
      get_url:
        url: https://tpo.pe/pathogen.vim
        dest: ~/.vim/autoload/pathogen.vim

    - name: clone vim plugins
      git:
        repo: '{{ item }}'
        dest: '~/.vim/bundle/{{ item | basename | replace(".git", "") }}'
      with_items:
        - git://github.com/bronson/vim-trailing-whitespace
        - git://github.com/dagwieers/asciidoc-vim
        - git://github.com/dcharbon/vim-flatbuffers
        - git://github.com/derekwyatt/vim-scala
        - git://github.com/fatih/vim-go
        - git://github.com/jtratner/vim-flavored-markdown
        - git://github.com/honza/dockerfile.vim
        - git://github.com/leshill/vim-json
        - git://github.com/rust-lang/rust.vim
        - git://github.com/tpope/vim-endwise
        - git://github.com/tpope/vim-fugitive
        - git://github.com/tpope/vim-haml
        - git://github.com/tpope/vim-markdown
        - git://github.com/tpope/vim-surround
        - git://github.com/vim-ruby/vim-ruby
        - git://github.com/ctrlpvim/ctrlp.vim
        - git://github.com/Valloric/YouCompleteMe

    - name: clone git-helpers
      git:
        repo: git://github.com/jsternberg/git-helpers
        dest: '~/git-helpers'

    - name: copy .vimrc
      copy:
        src: files/vimrc
        dest: ~/.vimrc
        backup: yes

    - name: copy .tmux.conf
      template:
        src: files/tmux.conf
        dest: ~/.tmux.conf
        backup: yes

    - name: copy .gitconfig
      template:
        src: files/gitconfig.j2
        dest: ~/.gitconfig
        backup: yes

    - name: copy .gitignore_global
      template:
        src: files/gitignore_global
        dest: ~/.gitignore_global
        backup: yes

    - name: create ~/go/bin directory
      file:
        path: ~/go/bin
        recurse: yes
        state: directory

    - name: install go tools
      command: 'go get -u {{ item }}'
      with_items:
        - github.com/fatih/gomodifytags
        - golang.org/x/tools/cmd/benchcmp
        - golang.org/x/tools/cmd/goimports
        - golang.org/x/tools/cmd/gorename
      environment:
        GOPATH: '{{ ansible_env.HOME }}/go'

    - name: create ~/.config/fish directory
      file:
        path: ~/.config/fish
        recurse: yes
        state: directory

    - name: copy fish/config.fish
      template:
        src: files/fish/config.fish
        dest: ~/.config/fish/config.fish
        backup: yes

    - name: create ~/.config/fish/completions directory
      file:
        path: ~/.config/fish/completions
        state: directory

    - name: copy custom fish completions
      copy:
        src: 'files/fish/{{ item }}'
        dest: '~/.config/fish/completions/{{ item }}'
      with_items:
        - git.fish
