set ignorecase
set smartcase
set incsearch
set nohlsearch

set tabstop=2
set shiftwidth=2
set smarttab
set expandtab
set softtabstop=2
set autoindent
set modeline
set modelines=5
set ruler
set backspace=2
set hidden

set shell=bash

if has("autocmd")
  autocmd Filetype markdown setlocal tw=72
  autocmd Filetype python setlocal ts=4 sts=4 sw=4
  autocmd Filetype go setlocal ts=4 sts=4 sw=4 noexpandtab
  autocmd Filetype java setlocal ts=4 sts=4 sw=4
  autocmd Filetype rust setlocal ts=4 sts=4 sw=4

  autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
  autocmd InsertLeave * if pumvisible() == 0|pclose|endif
  nmap ;c :lclose<CR>

  au BufRead,BufNewFile *.jelly set filetype=xml
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif

  autocmd Filetype go nmap <C-l>d :GeDoc .<CR>
  autocmd Filetype go nmap <C-l>i :GoImplements<CR>
  autocmd Filetype go nmap <C-l>c :GoCallees<CR>
  autocmd Filetype go nmap <C-l>r :GoReferrers<CR>
  autocmd Filetype go nmap <C-t> :GoAlternate<CR>
  autocmd Filetype go nmap <C-{> :lp<CR>
  autocmd Filetype go nmap <C-}> :lne<CR>
  let g:go_fmt_command = "goimports"
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_build_constraints = 1
  let g:go_highlight_generate_tags = 1
endif

if executable("ag")
  set grepprg=ag\ --nogroup\ --nocolor
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
  let g:ctrlp_use_caching = 0
endif

"nmap <C-n> :NERDTreeToggle<CR>
nmap <C-n> :TagbarToggle<CR>
inoremap <C-d> <Esc>

execute pathogen#infect()
syntax on
filetype plugin indent on
